import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { sql } from '@/lib/db';

export async function POST(req: NextRequest) {
    try {
        const { lessonData, lessonId } = await req.json();

        // Check for API keys
        const gammaApiKey = process.env.GAMMA_API_KEY;
        const anthropicApiKey = process.env.ANTHROPIC_API_KEY;

        if (!gammaApiKey) {
            throw new Error('Gamma API key not configured');
        }

        if (!anthropicApiKey) {
            throw new Error('Anthropic API key not configured');
        }

        // Step 1: Use Claude to create thoughtful, participant-focused presentation content
        console.log('🤖 Using Claude AI to design presentation...');
        const presentationContent = await generatePresentationWithClaude(lessonData, anthropicApiKey);

        console.log('✅ Presentation content generated by Claude');

        // Step 2: Send to Gamma for beautiful formatting
        const response = await fetch('https://public-api.gamma.app/v1.0/generations', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-API-KEY': gammaApiKey,
            },
            body: JSON.stringify({
                inputText: presentationContent,
                textMode: 'preserve', // Keep Claude's thoughtful content as-is
                format: 'presentation',
                numCards: 12, // Flexible number of slides
                cardSplit: 'inputTextBreaks',
                textOptions: {
                    amount: 'detailed',
                    tone: 'professional, warm, supportive',
                    audience: 'individuals in recovery, peer support groups',
                    language: 'en'
                },
                cardOptions: {
                    dimensions: 'fluid'
                },
                imageOptions: {
                    source: 'aiGenerated', // Let Gamma add relevant images
                    style: 'warm, hopeful, supportive'
                }
            }),
        });

        if (!response.ok) {
            const errorData = await response.json();
            console.error('Gamma API Error:', errorData);
            throw new Error(`Gamma API error: ${errorData.message || JSON.stringify(errorData)}`);
        }

        const data = await response.json();
        const generationId = data.id || data.generationId;

        if (!generationId) {
            throw new Error('No generation ID returned from Gamma API');
        }

        // Poll for completion
        let attempts = 0;
        const maxAttempts = 120;
        let gammaUrl = null;
        let lastStatus = '';

        console.log(`Polling for generation ${generationId}...`);

        while (attempts < maxAttempts && !gammaUrl) {
            await new Promise(resolve => setTimeout(resolve, 2000));

            const statusResponse = await fetch(
                `https://public-api.gamma.app/v1.0/generations/${generationId}`,
                {
                    headers: {
                        'X-API-KEY': gammaApiKey,
                    },
                }
            );

            if (statusResponse.ok) {
                const statusData = await statusResponse.json();
                lastStatus = statusData.status || 'unknown';

                console.log(`Attempt ${attempts + 1}: Status = ${lastStatus}`);

                const url = statusData.webUrl ||
                    statusData.gamma_url ||
                    statusData.gammaUrl ||
                    statusData.url ||
                    statusData.publicUrl;

                if (lastStatus === 'completed' && url) {
                    gammaUrl = url;
                    console.log(`Generation completed! URL: ${gammaUrl}`);
                    break;
                } else if (lastStatus === 'failed' || lastStatus === 'error') {
                    const errorMsg = statusData.error || statusData.errorMessage || 'Generation failed';
                    throw new Error(`Gamma generation failed: ${errorMsg}`);
                }
            } else {
                console.error(`Status check failed: ${statusResponse.status}`);
            }

            attempts++;
        }

        if (!gammaUrl) {
            throw new Error(
                `Generation is still processing (Status: ${lastStatus}). ` +
                `Check Gamma workspace or try again in a moment. Generation ID: ${generationId}`
            );
        }

        // Step 3: Save Gamma URL to Neon database if lessonId provided
        if (lessonId) {
            try {
                console.log('📝 Updating database for lesson:', lessonId);
                console.log('🔗 URL to save:', gammaUrl);

                await sql`
                    UPDATE saved_lessons
                    SET 
                        gamma_presentation_url = ${gammaUrl},
                        updated_at = NOW()
                    WHERE id = ${lessonId}::uuid
                `;

                console.log('✅ Gamma URL saved to database for lesson:', lessonId);
            } catch (dbError) {
                console.error('❌ Database update error:', dbError);
                // Continue anyway - presentation was generated successfully
            }
        }

        return NextResponse.json({
            success: true,
            gammaUrl: gammaUrl,
            generationId: generationId,
            message: 'AI-powered presentation generated successfully!'
        });

    } catch (error) {
        console.error('Error generating Gamma presentation:', error);
        return NextResponse.json(
            {
                error: 'Failed to generate presentation',
                details: error instanceof Error ? error.message : 'Unknown error'
            },
            { status: 500 }
        );
    }
}

// Use Claude AI to intelligently design presentation slides
async function generatePresentationWithClaude(lessonData: any, apiKey: string): Promise<string> {
    const anthropic = new Anthropic({ apiKey });

    const {
        title,
        overview,
        objectives,
        activities,
        discussionPrompts,
        sessionType,
        sessionLength,
    } = lessonData;

    const prompt = `You are an expert peer support facilitator creating a professional presentation for a recovery support session.

LESSON DETAILS:
Title: ${title}
Duration: ${sessionLength} minutes
Type: ${sessionType === 'group' ? 'Group session' : 'Individual session'}

Overview: ${overview}

Learning Objectives:
${objectives?.map((obj: string) => `- ${obj}`).join('\n') || 'Not specified'}

Activities:
${activities?.map((act: any) => `- ${act.name} (${act.duration}): ${act.description}`).join('\n') || 'Not specified'}

Discussion Prompts:
${discussionPrompts?.map((prompt: string) => `- ${prompt}`).join('\n') || 'Not specified'}

---

CREATE A PRESENTATION FOR PARTICIPANTS (not a facilitator guide). The presentation should:

1. Be designed for the AUDIENCE to see during the session
2. Have clean, engaging slides with just enough content
3. Support the facilitator without overwhelming participants
4. Use warm, supportive, recovery-appropriate language
5. Be visually organized and easy to follow

STRUCTURE (use --- to separate slides):

Slide 1: Title slide with session name and welcoming subtitle
Slide 2: "Today's Focus" - Rewrite the overview in engaging, participant-friendly language
Slide 3: "What We'll Accomplish Together" - List the objectives
Slide 4: "Session Agenda" - List the activities with times
Slides 5-X: One slide per main activity/topic with:
  - Clear heading
  - 2-4 key points or concepts
  - Thoughtful content that invites reflection
Slide Y: "Let's Discuss" - 3-4 best discussion prompts from the list
Final Slide: "Closing Thoughts" - Brief, hopeful closing message

IMPORTANT:
- NO facilitator notes, materials lists, or "behind the scenes" content
- Keep text concise and visual
- Use encouraging, non-judgmental language
- Focus on hope, growth, and connection
- Make it presentation-ready

Format with markdown headings (## for slide titles) and use --- between slides.

Generate the presentation content now:`;

    const message = await anthropic.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        messages: [
            {
                role: 'user',
                content: prompt
            }
        ]
    });

    const content = message.content[0];
    if (content.type === 'text') {
        return content.text;
    }

    throw new Error('Unexpected response format from Claude');
}
