// ============================================================================
// /api/generate-gamma/route.ts — Streaming version
//
// Three long-running phases:
//   1. Claude generates presentation content (~10-20s)
//   2. Gamma API submission (~2-5s)
//   3. Gamma polling for completion (~30-120s)
//
// Sends keep-alive pings every 5s + status updates at each phase.
//
// Wire format (newline-delimited JSON):
//   {"type":"ping"}
//   {"type":"status","message":"..."}
//   {"type":"result","success":true,"gammaUrl":"...","generationId":"..."}
//   {"type":"error","message":"..."}
// ============================================================================

import { NextRequest } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { sql } from '@/lib/db';

export async function POST(req: NextRequest) {
    const encoder = new TextEncoder();

    const stream = new ReadableStream({
        async start(controller) {
            const send = (obj: Record<string, any>) => {
                controller.enqueue(encoder.encode(JSON.stringify(obj) + '\n'));
            };

            // Keep-alive: ping every 5s so the connection stays open
            const pingInterval = setInterval(() => {
                try {
                    send({ type: 'ping' });
                } catch {
                    clearInterval(pingInterval);
                }
            }, 5000);

            try {
                const { lessonData, lessonId } = await req.json();

                const gammaApiKey = process.env.GAMMA_API_KEY;
                const anthropicApiKey = process.env.ANTHROPIC_API_KEY;

                if (!gammaApiKey) {
                    throw new Error('Gamma API key not configured');
                }
                if (!anthropicApiKey) {
                    throw new Error('Anthropic API key not configured');
                }

                // ── Step 1: Claude generates presentation content ──
                send({ type: 'status', message: 'AI is designing your presentation...' });
                console.log('🤖 Using Claude AI to design presentation...');

                const presentationContent = await generatePresentationWithClaude(lessonData, anthropicApiKey);
                console.log('✅ Presentation content generated by Claude');

                // ── Step 2: Send to Gamma for formatting ──
                send({ type: 'status', message: 'Sending to Gamma for formatting...' });

                const response = await fetch('https://public-api.gamma.app/v1.0/generations', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-API-KEY': gammaApiKey,
                    },
                    body: JSON.stringify({
                        inputText: presentationContent,
                        textMode: 'preserve',
                        format: 'presentation',
                        numCards: 12,
                        cardSplit: 'inputTextBreaks',
                        textOptions: {
                            amount: 'detailed',
                            tone: 'professional, warm, supportive',
                            audience: 'individuals in recovery, peer support groups',
                            language: 'en'
                        },
                        cardOptions: {
                            dimensions: 'fluid'
                        },
                        imageOptions: {
                            source: 'aiGenerated',
                            style: 'warm, hopeful, supportive'
                        }
                    }),
                });

                if (!response.ok) {
                    const errorData = await response.json();
                    console.error('Gamma API Error:', errorData);
                    throw new Error(`Gamma API error: ${errorData.message || JSON.stringify(errorData)}`);
                }

                const data = await response.json();
                const generationId = data.id || data.generationId;

                if (!generationId) {
                    throw new Error('No generation ID returned from Gamma API');
                }

                // ── Step 3: Poll for completion ──
                send({ type: 'status', message: 'Gamma is building your slides...' });
                console.log(`Polling for generation ${generationId}...`);

                let attempts = 0;
                const maxAttempts = 120;
                let gammaUrl = null;
                let lastStatus = '';

                while (attempts < maxAttempts && !gammaUrl) {
                    await new Promise(resolve => setTimeout(resolve, 2000));

                    const statusResponse = await fetch(
                        `https://public-api.gamma.app/v1.0/generations/${generationId}`,
                        {
                            headers: {
                                'X-API-KEY': gammaApiKey,
                            },
                        }
                    );

                    if (statusResponse.ok) {
                        const statusData = await statusResponse.json();
                        lastStatus = statusData.status || 'unknown';
                        console.log(`Attempt ${attempts + 1}: Status = ${lastStatus}`);

                        // Send periodic progress updates to the frontend
                        if (attempts > 0 && attempts % 5 === 0) {
                            send({ type: 'status', message: `Still building slides... (${attempts * 2}s)` });
                        }

                        const url = statusData.webUrl ||
                            statusData.gamma_url ||
                            statusData.gammaUrl ||
                            statusData.url ||
                            statusData.publicUrl;

                        if (lastStatus === 'completed' && url) {
                            gammaUrl = url;
                            console.log(`Generation completed! URL: ${gammaUrl}`);
                            break;
                        } else if (lastStatus === 'failed' || lastStatus === 'error') {
                            const errorMsg = statusData.error || statusData.errorMessage || 'Generation failed';
                            throw new Error(`Gamma generation failed: ${errorMsg}`);
                        }
                    } else {
                        console.error(`Status check failed: ${statusResponse.status}`);
                    }

                    attempts++;
                }

                if (!gammaUrl) {
                    throw new Error(
                        `Generation is still processing (Status: ${lastStatus}). ` +
                        `Check Gamma workspace or try again in a moment. Generation ID: ${generationId}`
                    );
                }

                // ── Step 4: Save to database ──
                if (lessonId) {
                    try {
                        send({ type: 'status', message: 'Saving presentation link...' });
                        console.log('📝 Updating database for lesson:', lessonId);

                        await sql`
                            UPDATE saved_lessons
                            SET 
                                gamma_presentation_url = ${gammaUrl},
                                updated_at = NOW()
                            WHERE id = ${lessonId}::uuid
                        `;

                        console.log('✅ Gamma URL saved to database for lesson:', lessonId);
                    } catch (dbError) {
                        console.error('❌ Database update error:', dbError);
                        // Continue — presentation was generated successfully
                    }
                }

                // ── Send final result ──
                send({
                    type: 'result',
                    success: true,
                    gammaUrl,
                    generationId,
                    message: 'AI-powered presentation generated successfully!',
                });

            } catch (error) {
                console.error('Error generating Gamma presentation:', error);
                send({
                    type: 'error',
                    message: error instanceof Error ? error.message : 'Unknown error',
                });
            } finally {
                clearInterval(pingInterval);
                controller.close();
            }
        },
    });

    return new Response(stream, {
        headers: {
            'Content-Type': 'text/plain; charset=utf-8',
            'Cache-Control': 'no-cache',
            'Transfer-Encoding': 'chunked',
        },
    });
}

// Use Claude AI to intelligently design presentation slides
async function generatePresentationWithClaude(lessonData: any, apiKey: string): Promise<string> {
    const anthropic = new Anthropic({ apiKey });

    const {
        title,
        overview,
        objectives,
        activities,
        discussionPrompts,
        sessionType,
        sessionLength,
    } = lessonData;

    const prompt = `You are an expert peer support facilitator creating a professional presentation for a recovery support session.

LESSON DETAILS:
Title: ${title}
Duration: ${sessionLength} minutes
Type: ${sessionType === 'group' ? 'Group session' : 'Individual session'}

Overview: ${overview}

Learning Objectives:
${objectives?.map((obj: string) => `- ${obj}`).join('\n') || 'Not specified'}

Activities:
${activities?.map((act: any) => `- ${act.name} (${act.duration}): ${act.description}`).join('\n') || 'Not specified'}

Discussion Prompts:
${discussionPrompts?.map((prompt: string) => `- ${prompt}`).join('\n') || 'Not specified'}

---

CREATE A PRESENTATION FOR PARTICIPANTS (not a facilitator guide). The presentation should:

1. Be designed for the AUDIENCE to see during the session
2. Have clean, engaging slides with just enough content
3. Support the facilitator without overwhelming participants
4. Use warm, supportive, recovery-appropriate language
5. Be visually organized and easy to follow

STRUCTURE (use --- to separate slides):

Slide 1: Title slide with session name and welcoming subtitle
Slide 2: "Today's Focus" - Rewrite the overview in engaging, participant-friendly language
Slide 3: "What We'll Accomplish Together" - List the objectives
Slide 4: "Session Agenda" - List the activities with times
Slides 5-X: One slide per main activity/topic with:
  - Clear heading
  - 2-4 key points or concepts
  - Thoughtful content that invites reflection
Slide Y: "Let's Discuss" - 3-4 best discussion prompts from the list
Final Slide: "Closing Thoughts" - Brief, hopeful closing message

IMPORTANT:
- NO facilitator notes, materials lists, or "behind the scenes" content
- Keep text concise and visual
- Use encouraging, non-judgmental language
- Focus on hope, growth, and connection
- Make it presentation-ready

Format with markdown headings (## for slide titles) and use --- between slides.

Generate the presentation content now:`;

    const message = await anthropic.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        messages: [
            {
                role: 'user',
                content: prompt
            }
        ]
    });

    const content = message.content[0];
    if (content.type === 'text') {
        return content.text;
    }

    throw new Error('Unexpected response format from Claude');
}
