// ============================================================================
// /app/api/generate-gamma/start/route.ts
//
// Kicks off Gamma presentation generation.
//   1. Claude generates slide content      (~10–20s)
//   2. Gamma API submission                 (~2–5s)
//   Total: ~15–25s — fits under the Amplify SSR Lambda 30s wall.
//
// Returns the Gamma generationId immediately. The client then polls
// /api/generate-gamma/status to wait for completion.
// ============================================================================

import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';

export async function POST(req: NextRequest) {
    try {
        const { lessonData, lessonId } = await req.json();

        const gammaApiKey = process.env.GAMMA_API_KEY;
        const anthropicApiKey = process.env.ANTHROPIC_API_KEY;

        if (!gammaApiKey) {
            return NextResponse.json(
                { error: 'Gamma API key not configured' },
                { status: 500 }
            );
        }
        if (!anthropicApiKey) {
            return NextResponse.json(
                { error: 'Anthropic API key not configured' },
                { status: 500 }
            );
        }
        if (!lessonData) {
            return NextResponse.json(
                { error: 'Missing lessonData in request body' },
                { status: 400 }
            );
        }

        // ── Step 1: Claude generates presentation content ──
        console.log('🤖 Using Claude AI to design presentation...');
        const presentationContent = await generatePresentationWithClaude(
            lessonData,
            anthropicApiKey
        );
        console.log('✅ Presentation content generated by Claude');

        // ── Step 2: Submit to Gamma ──
        const response = await fetch('https://public-api.gamma.app/v1.0/generations', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-API-KEY': gammaApiKey,
            },
            body: JSON.stringify({
                inputText: presentationContent,
                textMode: 'preserve',
                format: 'presentation',
                numCards: 12,
                cardSplit: 'inputTextBreaks',
                textOptions: {
                    amount: 'detailed',
                    tone: 'professional, warm, supportive',
                    audience: 'individuals in recovery, peer support groups',
                    language: 'en',
                },
                cardOptions: {
                    dimensions: 'fluid',
                },
                imageOptions: {
                    source: 'aiGenerated',
                    style: 'warm, hopeful, supportive',
                },
            }),
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            console.error('Gamma API Error:', errorData);
            return NextResponse.json(
                {
                    error: 'Gamma API error',
                    details: errorData.message || JSON.stringify(errorData),
                },
                { status: 500 }
            );
        }

        const data = await response.json();
        const generationId = data.id || data.generationId;

        if (!generationId) {
            return NextResponse.json(
                { error: 'No generation ID returned from Gamma API' },
                { status: 500 }
            );
        }

        console.log(`✅ Gamma generation started: ${generationId} (lesson: ${lessonId || 'none'})`);

        return NextResponse.json({
            success: true,
            generationId,
            status: 'pending',
        });
    } catch (error) {
        console.error('Error starting Gamma generation:', error);
        return NextResponse.json(
            {
                error: 'Failed to start presentation generation',
                details: error instanceof Error ? error.message : String(error),
            },
            { status: 500 }
        );
    }
}

// Use Claude AI to design participant-facing slide content
async function generatePresentationWithClaude(
    lessonData: any,
    apiKey: string
): Promise<string> {
    const anthropic = new Anthropic({ apiKey });

    const {
        title,
        overview,
        objectives,
        activities,
        discussionPrompts,
        sessionType,
        sessionLength,
    } = lessonData;

    const prompt = `You are an expert peer support facilitator creating a professional presentation for a recovery support session.

LESSON DETAILS:
Title: ${title}
Duration: ${sessionLength} minutes
Type: ${sessionType === 'group' ? 'Group session' : 'Individual session'}

Overview: ${overview}

Learning Objectives:
${objectives?.map((obj: string) => `- ${obj}`).join('\n') || 'Not specified'}

Activities:
${activities?.map((act: any) => `- ${act.name} (${act.duration}): ${act.description}`).join('\n') || 'Not specified'}

Discussion Prompts:
${discussionPrompts?.map((prompt: string) => `- ${prompt}`).join('\n') || 'Not specified'}

---

CREATE A PRESENTATION FOR PARTICIPANTS (not a facilitator guide). The presentation should:

1. Be designed for the AUDIENCE to see during the session
2. Have clean, engaging slides with just enough content
3. Support the facilitator without overwhelming participants
4. Use warm, supportive, recovery-appropriate language
5. Be visually organized and easy to follow

STRUCTURE (use --- to separate slides):

Slide 1: Title slide with session name and welcoming subtitle
Slide 2: "Today's Focus" - Rewrite the overview in engaging, participant-friendly language
Slide 3: "What We'll Accomplish Together" - List the objectives
Slide 4: "Session Agenda" - List the activities with times
Slides 5-X: One slide per main activity/topic with:
  - Clear heading
  - 2-4 key points or concepts
  - Thoughtful content that invites reflection
Slide Y: "Let's Discuss" - 3-4 best discussion prompts from the list
Final Slide: "Closing Thoughts" - Brief, hopeful closing message

IMPORTANT:
- NO facilitator notes, materials lists, or "behind the scenes" content
- Keep text concise and visual
- Use encouraging, non-judgmental language
- Focus on hope, growth, and connection
- Make it presentation-ready

Format with markdown headings (## for slide titles) and use --- between slides.

Generate the presentation content now:`;

    const message = await anthropic.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        messages: [
            {
                role: 'user',
                content: prompt,
            },
        ],
    });

    const content = message.content[0];
    if (content.type === 'text') {
        return content.text;
    }

    throw new Error('Unexpected response format from Claude');
}
